source 'https://rubygems.org'

gem 'rails', '3.2.13'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mysql2'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'

gem 'heroku'
gem 'devise'
gem 'omniauth'
gem 'rails_admin'
gem 'haml-rails'
gem 'paperclip'

group :production do
  gem 'aws-sdk'
end

group :development, :test do
  gem 'html2haml'
  gem 'erb2haml'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'database_cleaner'	
end

gem 'exifr'
gem 'sidekiq'


gem 'slim', '>= 1.1.0'
gem 'sinatra', '>= 1.3.0', :require => nil


gem 'omniauth'
gem 'omniauth-facebook'
